### ISSUE TITLE
Spark Backend Tests Fail during Staging with New Scalan-Lite 2.11-SNAPSHOT

### ISSUE THREAD

**Issue by PCMNN** [scalan/scalan-spark#1]
Specifically, tests in spark-backend/BackendTests.scala fail. Probably, due to inability to find extE in TypeWrapper for SparkContext.

**Comment by PCMNN** [comment]
Log:
[info] BackendTests:
[info] - Broadcast/RDD Code Gen **\* FAILED ***
[info]   scala.ScalaReflectionException: Failed to find the field corresponding to TypeWrappersExp.this.ExpBaseElemEx.extE
[info]   at scalan.util.ReflectionUtil$$anonfun$paramFieldMirrors$1$$anonfun$6.apply(ReflectionUtil.scala:67)
[info]   at scalan.util.ReflectionUtil$$anonfun$paramFieldMirrors$1$$anonfun$6.apply(ReflectionUtil.scala:67)
[info]   at scala.Option.getOrElse(Option.scala:120)
[info]   at scalan.util.ReflectionUtil$$anonfun$paramFieldMirrors$1.apply(ReflectionUtil.scala:66)
[info]   at scalan.util.ReflectionUtil$$anonfun$paramFieldMirrors$1.apply(ReflectionUtil.scala:49)
[info]   at scala.collection.immutable.List.map(List.scala:272)
[info]   at scalan.util.ReflectionUtil$.paramFieldMirrors(ReflectionUtil.scala:49)
[info]   at scalan.compilation.lms.LmsBridge$class.scalan$compilation$lms$LmsBridge$$reflectElement(LmsBridge.scala:241)
[info]   at scalan.compilation.lms.LmsBridge$$anonfun$12.apply(LmsBridge.scala:283)
[info]   at scalan.compilation.lms.LmsBridge$$anonfun$12.apply(LmsBridge.scala:283)
[info]   ...

**Comment by PCMNN** [comment]
@alexeyr, please look into this issue.

**Comment by alexeyr** [comment]
Yes, extE isn't a field. Add a case for `ExpBaseElemEx` to `LmsBridge.elemToManifest`, should be similar to one for `ExpBaseElemEx1`.

**Comment by PCMNN** [comment]
It has resolved the issue. Thank you!
